### PR TITLE
adds and implements loop

### PR DESCRIPTION
**Pull request by kyleshevlin**
Implements `loop` as discussed in #7

There may be more work than this. There's no tests for me to run and I'm not sure how to verify that this works as expected. Let's start here, and make the additional changes necessary.

Sorry it took me so long to get to this.

### CODE REVIEW

**Comment by jmeistrich** [comment]
Thanks @kyleshevlin! This looks like a good solution. I'm traveling at the moment so just need another day or two to give it a good run, but it's short and straightforward so I expect it should be good to merge.

**Comment by jmeistrich** [comment]
@kyleshevlin I just pushed a couple tweaks to the PR, hope you don't mind! I added an example of Looping to the example app and it seems to be working well. Does it look good to you? I think it's good to merge and release an update with it.

I did not do a great job of writing tests for this project. I use the Example app as a way of manually testing it. If you (or someone) would like to write good tests it would be much appreciated! Or I will try to get to it some time after we finish getting Legend-State to 1.0.

**Comment by kyleshevlin** [comment]
I don't mind at all. I made it editable by you on purpose. 👍🏻

**Comment by rozhover** [comment]
Can this get merged? Would love to use this :)

**Comment by jmeistrich** [comment]
Sorry for the delay! My laptop broke near the end of a trip to New Zealand, so I can't release a package update for about 5 more days, but then will do so as soon as I can 👍

**Pull request merged**
